### ISSUE TITLE
pytorch_lite/android /CMakeLists.txt problem

### ISSUE THREAD

**Issue by ZhaoXinZhang** [zezo357/pytorch_lite#26] opened 2023-07-14 16:40 UTC
In pytorch_lite/android /CMakeLists.txt I have two problem.

1.
66 Columns
` COMMAND wget -O "${LIBTORCH_ARCHIVE}" "${LIBTORCH_URL}"` 
It failed because wget is not bulit-in command. should use wget command to download libtorch-android.zip? thanks

2.
80 Columns
`COMMAND unzip -o "${LIBTORCH_ARCHIVE}" -d "${LIBTORCH_SRC}"`
It fail too. Is it can be change to `COMMAND tar -xvf "${LIBTORCH_ARCHIVE}" -C "${LIBTORCH_SRC}"` ? thanks.

**Comment by zezo357** [comment] 2023-07-14 17:44
Will check if I can improve it, thank you for your feedback, can you make a pr with the improvement if you can?

**Comment by ZhaoXinZhang** [comment] 2023-07-15 16:36
OK, I make pr, this is my first pr, so please check result, tks.

**Comment by zezo357** [comment] 2023-07-15 16:57
Thank you, will check when I got time, btw it should run in macos and windows, so I hope it does

**Comment by mibcoder** [comment] 2023-07-20 10:33
@zezo357 @ZhaoXinZhang 
 
I am also getting error on download,


I have changed **COMMAND unzip -o "${LIBTORCH_ARCHIVE}" -d "${LIBTORCH_SRC}"** to **COMMAND tar -xvf "${LIBTORCH_ARCHIVE}" -C "${LIBTORCH_SRC}"**

But not work

Here is error:

  CMake Error at CMakeLists.txt:70 (message):
    Download of libtorch-android.zip failed.

**Comment by mibcoder** [comment] 2023-07-20 10:36
@ZhaoXinZhang seem like problem at this line

COMMAND wget -O "${LIBTORCH_ARCHIVE}" "${LIBTORCH_URL}"

**Comment by zezo357** [comment] 2023-07-20 10:42
> @ZhaoXinZhang seem like problem at this line
> 
> COMMAND wget -O "${LIBTORCH_ARCHIVE}" "${LIBTORCH_URL}"
> 
> 

Yeah, will work on the Pr mentioning the problem at night, and hopefully everything goes well,

Sorry for any inconveniences

**Comment by ZhaoXinZhang** [comment] 2023-07-20 11:41
> @zezo357 @ZhaoXinZhang 
>  
> I am also getting error on download,
> 
> 
> I have changed **COMMAND unzip -o "${LIBTORCH_ARCHIVE}" -d "${LIBTORCH_SRC}"** to **COMMAND tar -xvf "${LIBTORCH_ARCHIVE}" -C "${LIBTORCH_SRC}"**
> 
> But not work
> 
> Here is error:
> 
>   CMake Error at CMakeLists.txt:70 (message):
>     Download of libtorch-android.zip failed.

Hi, if you want to use wget download the file, you must install wget first.

**Comment by zezo357** [comment] 2023-07-20 11:59
> > @zezo357 @ZhaoXinZhang 
> >  
> > I am also getting error on download,
> > 
> > 
> > I have changed **COMMAND unzip -o "${LIBTORCH_ARCHIVE}" -d "${LIBTORCH_SRC}"** to **COMMAND tar -xvf "${LIBTORCH_ARCHIVE}" -C "${LIBTORCH_SRC}"**
> > 
> > But not work
> > 
> > Here is error:
> > 
> >   CMake Error at CMakeLists.txt:70 (message):
> >     Download of libtorch-android.zip failed.
> 
> Hi, if you want to use wget download the file, you must install wget first.

Yes, looks like it was installed on my PC, which is the main problem, so I will try another fixes or provide help code to install it

**Comment by zezo357** [comment] 2023-07-20 13:56
hello @ZhaoXinZhang @mibcoder , just added github actions to test on both macos and windows for building android

both are passing in 3.0.1 , can you guys check and let me know? for the pr i think that we dont need to change the extraction method, but let me know if its causes problems to try to find a fix,

in the future: i will try to add integration tests to make sure everything works on all platforms to make it easier for people

**Comment by zezo357** [comment] 2023-07-20 14:22
extraction updated in 3.0.2 check if everything it working as intended, keep in mind tar is not built in so i switched to powershell

**Comment by ZhaoXinZhang** [comment] 2023-07-20 14:38
> hello @ZhaoXinZhang @mibcoder , just added github actions to test on both macos and windows for building android
> 
> both are passing in 3.0.1 , can you guys check and let me know? for the pr i think that we dont need to change the extraction method, but let me know if its causes problems to try to find a fix,
> 
> in the future: i will try to add integration tests to make sure everything works on all platforms to make it easier for people

As of Windows 10 build 17063 though, Tar is now packaged in the OS by default.
ref: https://www.addictivetips.com/windows-tips/use-tar-on-windows-10/

Because 'unzip' is not recognized as a name of a cmdlet, function, script file, or executable program in my PC, but tar is. So I change the extraction method to tar command, and it is work.

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/839a7c2a-2a36-41a4-a7bb-44520097568e)

**Comment by ZhaoXinZhang** [comment] 2023-07-20 14:41
OK, I will try it

**Comment by ZhaoXinZhang** [comment] 2023-07-20 14:52
> > 3.0.2
> 
> 3.0.2 uses powershell it is integrated too, so check if that works for your case

Hi, I try 3.0.2 example project . It is still failed in extraction process. 

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/1d33c51f-3c1d-4de9-bbdf-ede26b9c9fdf)

**Comment by ZhaoXinZhang** [comment] 2023-07-20 15:35
It's OK. 
Btw, this is my first time report issues in github and I am use this project learning programing, so if any I can help, I will try.

**Comment by zezo357** [comment] 2023-07-20 20:21
hopefully release 3.0.3 fixes the issue, using tar as you mentioned since powershell was so slow it took 30+ min to build on github actions

**Comment by zezo357** [comment] 2023-07-20 20:23
@ZhaoXinZhang 3.0.3 is released let me know, if its finally works in your environment

**Comment by ZhaoXinZhang** [comment] 2023-07-21 03:02
> @ZhaoXinZhang 3.0.3 is released let me know, if its finally works in your environment

Hi, it work in my environment, I am not nearby my PC so I remote my PC and use emulator test.

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/b92c60bd-8841-4dc2-a982-dab16328bc3f)

**Comment by zezo357** [comment] 2023-07-21 03:48
Thank you for confirming, now we can close this issue and check the performance one

**Closed by zezo357** 2023-07-21 03:48 UTC
